spring.application.name=showCase

spring.profiles.active=h2
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

// this is for detailed logging / debugging output in console
// logging.level.org.springframework.security=DEBUG